USE sakila;

-- Challenge - Joining on multiple tables
-- 1.List the number of films per category.

 SELECT * FROM film_category;

SELECT 
    c.name AS category,
    COUNT(fc.film_id) AS total_films
FROM category AS c
INNER JOIN film_category AS fc
    ON c.category_id = fc.category_id
GROUP BY c.name;

-- 2. Retrieve the store ID, city, and country for each store.

SELECT s.store_id,
       ci.city,
       co.country
FROM store AS s
INNER JOIN address AS a
ON s.address_id = a.address_id
INNER JOIN city AS ci
ON a.city_id = ci.city_id
INNER JOIN country AS co
ON ci.country_id = co.country_id;

-- 3. Calculate the total revenue generated by each store in dollars.

SELECT s.store_id,
       SUM(p.amount) AS total_revenue
FROM payment AS p
INNER JOIN staff AS st
ON p.staff_id = st.staff_id
INNER JOIN store AS s
ON st.store_id = s.store_id
GROUP BY s.store_id;

-- 4. Determine the average running time of films for each category.

SELECT c.name AS category,
      ROUND(AVG(f.length), 2) AS average_running_time
FROM category AS c
INNER JOIN film_category AS fc
ON c.category_id = fc.category_id
INNER JOIN film AS f
ON fc.film_id = f.film_id
GROUP BY c.name;

-- 5. Identify the film categories with the longest average running time.

SELECT c.name AS category,
      ROUND(AVG(f.length), 2) AS average_running_time
FROM category AS c
INNER JOIN film_category AS fc
ON c.category_id = fc.category_id
INNER JOIN film AS f
ON fc.film_id = f.film_id
GROUP BY c.name
ORDER BY average_running_time DESC LIMIT 1;

-- 6. Display the top 10 most frequently rented movies in descending order.

SELECT f.title,
       COUNT(r.rental_id) AS rental_count
FROM film AS f
INNER JOIN inventory AS i
ON f.film_id = i.film_id
INNER JOIN rental AS r
ON i.inventory_id = r.inventory_id
GROUP BY f.title
ORDER BY rental_count DESC
LIMIT 10;

-- 7. Determine if "Academy Dinosaur" can be rented from Store 1.

SELECT 
    CASE
        WHEN COUNT(i.inventory_id) > 0 
        THEN 'Available'
        ELSE 'NOT Available'
    END AS availability
FROM film AS f
INNER JOIN inventory AS i
ON f.film_id = i.film_id
WHERE f.title = 'Academy Dinosaur'
AND i.store_id = 1;

-- 8. Provide a list of all distinct film titles, along with their availability status in the inventory...
SELECT DISTINCT f.title,
       CASE
           WHEN IFNULL(i.inventory_id, 0) = 0 
           THEN 'NOT available'
           ELSE 'Available'
       END AS availability
FROM film AS f
LEFT JOIN inventory AS i
ON f.film_id = i.film_id;
